### ISSUE TITLE
erl_graylog_sender:send/1 result

### ISSUE THREAD

**Issue by Aplicaty** [protofy/erl_graylog_sender#2]
erl_graylog_sender:send/1 always return ok. We need distinct between success and errors operations. How can we do it?

Thanks,

> MsgFull05 = [{host, "StJaviTorled.asua.fas.lan"}, {short_message, "Mensaje corto 04"}, {full_message, "Mensaje completo 04"}, {level, 6}, {campo_texto_01, "Valor campo texto 01 05"}, {campo_numerico_01, 15}].
> [{host,"StJaviTorled.asua.fas.lan"},
>  {short_message,"Mensaje corto 04"},
>  {full_message,"Mensaje completo 04"},
>  {level,6},
>  {campo_texto_01,"Valor campo texto 01 05"},
>  {campo_numerico_01,15}]
> erl_graylog_sender:send(MsgFull05).  
> ok

and in erlang.log.1 file ...

===== Fri Nov 20 14:48:10 CET 2015

=ERROR REPORT==== 20-Nov-2015::14:48:10 ===
*\* Generic server erl_graylog_sender terminating 
*\* Last message in was {'$gen_cast',
                           {send,
                               [{host,"StJaviTorled.asua.fas.lan"},
                                {short_message,"Mensaje corto 04"},
                                {full_message,"Mensaje completo 04"},
                                {level,6},
                                {campo_texto_01,"Valor campo texto 01 05"},
                                {campo_numerico_01,15}]}}
*\* When Server state == {state,gzip,0,
                               {#Port<0.2046>,"graylog.asua.fas.lan",5555},
                               erl_graylog_udp_sender,gelf,<<"StJaviTorled">>}
*\* Reason for termination == 
*\* {bad_return_value,{invalid,{key,"campo_texto_01"},prefix}}

===== ALIVE Fri Nov 20 15:03:10 CET 2015

**Comment by uuid0** [comment]
I've just added send_mode to erl_graylog_sender in master.

There now are the following send modes, which affect the result of send/1 and send/2:
- fire_and_forget -> always returns ok, malformed messages will just get ignored.
- validate_message -> returns ok or {error, Reason} if the message was malformed.
- ensure_delivery -> like validate_message but also waits for the return of SenderMod:send/2 and returns its value. You probably don't want to use this in production.

I think you want to use the send_mode validate_message in your case.

``` erlang
% [...]
Opts = [{send_mode, validate_message} | YourOpts],
erl_graylog_sender:start_link(Opts),
% [...]
```

or

``` erlang
% [...]
erl_graylog_sender:start_link(YourOpts),
erl_graylog_sender:set_opt(send_mode, validate_message),
% [...]
```

Does this solve your problem?

**Comment by Aplicaty** [comment]
I think so. Now just I have to try!

Thank you very much,
